# Generated by Claude Code. Preview for manual testing in dev: http://localhost:3000/rails/view_components/bar_chart_component/
#
# A grouped bar chart drawn with nothing but CSS, over semantic HTML that remains
# fully readable (and accessible) without the CSS: nested lists of label/value text.
# The bars themselves are generated by CSS pseudo-elements, so they add nothing to
# the accessibility tree; the visible numbers and labels _are_ the data.
#
#     <%= render BarChartComponent.new(
#           caption: "Items per month",
#           series: ["Created", "Published"],
#           groups: {
#             "July 2026"   => [210, 220],
#             "August 2026" => [240, 275]
#           }
#         ) %>
#
# Each group (eg month) gets one bar per series, side by side, with space before the next
# group. Values are shown below the bar, then the series label, then the group label.
#
# Styles are in app/frontend/stylesheets/local/bar_chart.scss, customizable with
# `--bar-chart-*` CSS custom properties.
#
# Heights are passed to CSS via inline `style` attributes (custom properties), so a
# Content-Security-Policy that forbids inline style attributes would prevent the bars
# from displaying (the text data would remain).
class BarChartComponent < ApplicationComponent
  attr_reader :series, :groups, :caption

  # @param series [Array<String>] names of the bars within each group, eg ["Created", "Published"]
  # @param groups [Hash{String => Array<Numeric,nil>}] group label => one value per series, in
  #   series order. nil value means "no data" (no bar, shown as an en dash).
  # @param caption [String] optional title for the chart, rendered as figcaption.
  # @param max [Numeric] optional value that equals a full-height bar; defaults to the
  #   largest value in the data. Pass the same max to multiple charts to make them comparable.
  def initialize(series:, groups:, caption: nil, max: nil)
    @series = series.to_a
    @groups = groups.to_h
    @caption = caption
    @max = max

    @groups.each do |label, values|
      unless values.is_a?(Array) && values.length == @series.length
        raise ArgumentError, "group #{label.inspect} needs #{@series.length} values (one per series), got #{values.inspect}"
      end
    end
  end

  # value that corresponds to a full-height bar
  def max
    @max || groups.values.flatten.compact.max || 0
  end

  def style_for_chart
    "--bar-chart-max: #{max.to_f};"
  end

  # nil value gets no bar
  def style_for_value(value)
    "--bar-chart-value: #{value.to_f};" unless value.nil?
  end

  def display_value(value)
    value.nil? ? "–" : helpers.number_with_delimiter(value)
  end
end
