# Note also the existence of resque-pool-special-worker.yml for special cases.

production:
  # "default" queue is mostly ingest-related at present.
  # "mailers" is specifically sending emails, which I guess we don't mind
  #    if they get queued up being ingest a big
  #
  # We generally only run 1 worker per dyno

  "mailers,default": <%= ScihistDigicoll::Env.lookup!(:regular_job_worker_count) %>

  # We run on_demand_derivatives in a different pool and different heroku dyno type

development:
  "*": 3
